version: '3.8'

services:
  mongo:
    image: mongo:7.0
    container_name: mongo
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network
    environment:
      MONGO_INITDB_DATABASE: urlshortener
    restart: always

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: always

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongo:27017/urlshortener
      - REDIS_HOST=redis  # Add Redis connection config
      - REDIS_PORT=6379
      - JWT_SECRET=123456
    depends_on:
      - mongo
      - redis  # Add Redis dependency
    networks:
      - app-network
    restart: always

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network
    restart: always

volumes:
  mongo_data:
    driver: local
  redis_data:  # Add Redis volume
    driver: local

networks:
  app-network:
    driver: bridge